"use client";

import { useCallback, useEffect, useState } from "react";

type Conversation = { conversation_id: string; title: string; message_count: number };
const API_BASE_URL = (process.env.NEXT_PUBLIC_API_URL ?? "").trim();
function apiUrl(path: string) { return API_BASE_URL ? new URL(path, API_BASE_URL).toString() : path; }

export default function ChatHistory({ courseId, activeConversationId, refreshKey, onSelect, onNew }: { courseId: string; activeConversationId: string | null; refreshKey: number; onSelect: (id: string) => void; onNew: () => void }) {
  const [conversations, setConversations] = useState<Conversation[]>([]);
  const [error, setError] = useState("");
  const load = useCallback(async () => { try { const response = await fetch(apiUrl(`/conversations?course_id=${encodeURIComponent(courseId)}`)); if (!response.ok) throw new Error("Unable to load previous chats."); setConversations((await response.json()).conversations ?? []); setError(""); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load previous chats."); } }, [courseId]);
  useEffect(() => { const timeoutId = setTimeout(() => void load(), 0); return () => clearTimeout(timeoutId); }, [load, refreshKey]);
  async function rename(conversation: Conversation) { const title = window.prompt("Rename chat", conversation.title)?.trim(); if (!title) return; const response = await fetch(apiUrl(`/conversations/${encodeURIComponent(conversation.conversation_id)}`), { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ course_id: courseId, title }) }); if (!response.ok) { setError("Unable to rename this chat."); return; } await load(); }
  async function remove(conversation: Conversation) { if (!window.confirm(`Delete ${conversation.title}? This cannot be undone.`)) return; const response = await fetch(apiUrl(`/conversations/${encodeURIComponent(conversation.conversation_id)}?course_id=${encodeURIComponent(courseId)}`), { method: "DELETE" }); if (!response.ok) { setError("Unable to delete this chat."); return; } if (conversation.conversation_id === activeConversationId) onNew(); await load(); }
  return <div style={{ display: "grid", gap: "0.9rem" }}><button type="button" onClick={onNew} style={{ border: 0, borderRadius: "999px", padding: "0.7rem 1rem", background: "#2563eb", color: "white", fontWeight: 700, cursor: "pointer" }}>+ New chat</button>{error && <p role="alert" style={{ margin: 0, color: "#b91c1c" }}>{error}</p>}{conversations.length === 0 ? <p style={{ margin: 0, color: "#475569", lineHeight: 1.5 }}>Your discussions will appear here.</p> : <div style={{ display: "grid", gap: "0.55rem", maxHeight: "520px", overflowY: "auto", paddingRight: "0.2rem" }}>{conversations.map((conversation) => <div key={conversation.conversation_id} style={{ display: "flex", gap: "0.3rem", borderRadius: "12px", background: conversation.conversation_id === activeConversationId ? "#dbeafe" : "#eff6ff" }}><button type="button" onClick={() => onSelect(conversation.conversation_id)} style={{ minWidth: 0, flex: 1, textAlign: "left", border: 0, borderRadius: "12px", padding: "0.75rem", background: "transparent", color: "#0f172a", cursor: "pointer" }}><strong style={{ display: "block", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{conversation.title}</strong><span style={{ fontSize: "0.82rem", color: "#475569" }}>{conversation.message_count} messages</span></button><button type="button" onClick={() => void rename(conversation)} aria-label={`Rename ${conversation.title}`} title="Rename chat" style={{ alignSelf: "center", border: 0, background: "transparent", color: "#1d4ed8", cursor: "pointer", padding: "0.45rem 0.35rem", fontSize: "1rem" }}>✎</button><button type="button" onClick={() => void remove(conversation)} aria-label={`Delete ${conversation.title}`} title="Delete chat" style={{ alignSelf: "center", border: 0, background: "transparent", color: "#dc2626", cursor: "pointer", padding: "0.45rem 0.55rem", fontSize: "1rem" }}>🗑</button></div>)}</div>}</div>;
}
